### ISSUE TITLE
Restore skipped

### ISSUE THREAD

**Issue by TobiasBuchholz** [DamianAntonowicz/CakeAndXamarinPlayground#2]
Hey Damian, thank you for this sample project and your presentation on the XamExpertDay, good stuff :)

I've tried the scripts in my own project and noticed the restore unfortunately gets skipped for the Android and iOS projects. Apparently the same applies to your sample project as well:

`/Users/tobiasbuchholz/Downloads/CakeAndXamarinPlayground-master/TastyFormsApp.Android/TastyFormsApp.Android.csproj : warning NU1503: Skipping restore for project '/Users/tobiasbuchholz/Downloads/CakeAndXamarinPlayground-master/TastyFormsApp.Android/TastyFormsApp.Android.csproj'. The project file may be invalid or missing targets required for restore. [/Users/tobiasbuchholz/Downloads/CakeAndXamarinPlayground-master/TastyFormsApp.sln]`

`/Users/tobiasbuchholz/Downloads/CakeAndXamarinPlayground-master/TastyFormsApp.iOS/TastyFormsApp.iOS.csproj : warning NU1503: Skipping restore for project '/Users/tobiasbuchholz/Downloads/CakeAndXamarinPlayground-master/TastyFormsApp.iOS/TastyFormsApp.iOS.csproj'. The project file may be invalid or missing targets required for restore. [/Users/tobiasbuchholz/Downloads/CakeAndXamarinPlayground-master/TastyFormsApp.sln]`

Do you have any idea how this could be solved?

**Comment by TobiasBuchholz** [comment]
Nevermind, I've just noticed the following lines in the other script samples which solve the problem:

`NuGetRestore(PATH_TO_IOS_PROJECT);`
`NuGetRestore(PATH_TO_ANDROID_PROJECT);`

**Comment by DamianAntonowicz** [comment]
Hi @TobiasBuchholz ! I'm glad you like the presentation :) Good that issue is resolved - if there are any other questions let me know :)
