### ISSUE TITLE
Step 2. Windows - .\build.ps1 -Target=RunUnitTests

### ISSUE THREAD

**Issue by JustickDM** [DamianAntonowicz/CakeAndXamarinPlayground#3]
Preparing to run build script...
Running build script...

Error: Unknown command 'RunUnitTests'.

       build.cake -Target=RunUnitTests
                          ^^^^^^^^^^^^ No such command

**Comment by DamianAntonowicz** [comment]
Hey @JustickDM,

Since [Cake 1.0.0](https://cakebuild.net/docs/getting-started/upgrade#cake-0.38.x-to-cake-1.0) you need to invoke target task like this:
```./build.sh --target=RunUnitTests```

Let me know if this solves the issue.

**Comment by JustickDM** [comment]
./build.sh --target=RunUnitTests - solving the issue.
